---
abstract: 'dynamically select error documents based on HTTP status code'
author:
  - 'Michael Jemmeson <michael.jemmeson@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Middleware::ErrorDocument: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-CustomErrorDocument
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Plack::Middleware::CustomErrorDocument:
    file: lib/Plack/Middleware/CustomErrorDocument.pm
    version: 0.004
requires:
  HTTP::Status: 0
  Plack::MIME: 0
  Plack::Middleware: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/mjemmeson/Plack-Middleware-CustomErrorDocument/issues
  homepage: https://github.com/mjemmeson/Plack-Middleware-CustomErrorDocument
  repository: https://github.com/mjemmeson/Plack-Middleware-CustomErrorDocument.git
version: 0.004
